version: '3'

services:
  redis-server:
    image: 'redis:latest'
  postrges:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  server:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - "3000:80"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=root
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432