apiVersion: skaffold/v2beta12
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: stephengrider/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
        '**/*.css': .
        '**/*.html': .
    - image: stephengrider/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
        sync:
          manual:
            - src: "*.js"
              dest: .
    - image: stephengrider/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
        sync:
          manual:
            - src: "*.js"
              dest: .

deploy:
  kubectl:
    manifests:
      - kuber/client-deployment.yml